export declare const WHITESPACE = " \u00A0\u00AD\u200B\u2060\u3000";
export declare const VALID_PUNCTUATION: string;
export declare const DIGITS: {
    '0': string;
    '1': string;
    '2': string;
    '3': string;
    '4': string;
    '5': string;
    '6': string;
    '7': string;
    '8': string;
    '9': string;
    '\uFF10': string;
    '\uFF11': string;
    '\uFF12': string;
    '\uFF13': string;
    '\uFF14': string;
    '\uFF15': string;
    '\uFF16': string;
    '\uFF17': string;
    '\uFF18': string;
    '\uFF19': string;
    '\u0660': string;
    '\u0661': string;
    '\u0662': string;
    '\u0663': string;
    '\u0664': string;
    '\u0665': string;
    '\u0666': string;
    '\u0667': string;
    '\u0668': string;
    '\u0669': string;
    '\u06F0': string;
    '\u06F1': string;
    '\u06F2': string;
    '\u06F3': string;
    '\u06F4': string;
    '\u06F5': string;
    '\u06F6': string;
    '\u06F7': string;
    '\u06F8': string;
    '\u06F9': string;
};
export declare const MAX_LENGTH_COUNTRY_CODE = 3;
export declare function extractCountryCallingCode(phoneNumber: any, country: any, metadata: any): {
    countryCallingCode?: undefined;
    phoneNumber?: undefined;
} | {
    countryCallingCode: any;
    phoneNumber: any;
};
export declare function matches_entirely(text: string, regularExpression: any): boolean;
export declare function parseDigit(character: any): any;
